Algoritmo "Classificacao-idade"
  //crie um programa que receba a idade da pessoa e a classifique de acordo
  //com a tabela:
Var

   idade: inteiro;

Inicio

    escreva("Quala sua idade?: ")
    leia(idade)
    se(idade < 18)entao
     escreval("Menor de indade!")
      senao
    se(idade >= 18) E (idade < 60)entao
     escreval("Adulto!")
      senao
     escreval("Idoso!")

    fimse
   fimse
Fimalgoritmo