Algoritmo "loginSenha"

Var
  nome: caractere
  senha: inteiro


Inicio

      repita
      escreva("Nome: ")
      leia(nome)
      escreva("Senha: ")
      leia(senha)
      se(senha = -1) entao
         escreval("Programa encerrado por solicitação do Usuário!")
         interrompa
      fimse
      
   ate (nome = "Marcos") e (senha = 1234)

   //nao sei se compreende corretamente

Fimalgoritmo